services:
  envoy:
    network_mode: "host"
    image: envoyproxy/envoy:v1.37-latest
    container_name: envoy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs:/etc/envoy/certs:ro
    #ports:
      #- "80:8080"
    depends_on:
      - opa
      - crypto-service
    #networks:
      #- envoy-mesh
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:latest-envoy
    container_name: opa
    volumes:
      - ./opa:/policy:ro
    command:
      - run
      - --server
      - --config-file=/policy/opa-config.yaml
      - /policy
    ports:
      - "127.0.0.1:9191:9191"
    networks:
      - envoy-mesh
    restart: unless-stopped

  crypto-service:
    build:
      context: ./crypto-service
    container_name: crypto-service         
    ports:
       - "8082:8082"
    networks:
      - envoy-mesh
    restart: unless-stopped

  db_pass:
    build: ./db_pass  # 假設你的 Flask 代碼在 db_pass 資料夾
    env_file:
      - .env
    container_name: db_pass
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - envoy-mesh

  # 2. 資料庫 (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}" # 配合你 app.py 的設定
      POSTGRES_DB: crypto_db
    volumes:
      # 資料持久化 (重開機資料還在)
      - postgres_data:/var/lib/postgresql/data
      # 初始化腳本 (自動建表)
      - ./sql_init.sql:/docker-entrypoint-initdb.d/sql_init.sql
    networks:
      - envoy-mesh

  # 3. 監控儀表板 (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - .env
    ports:
      - "3000:3000" # Grafana 預設跑在 3000 port
    depends_on:
      - postgres
    networks:
      - envoy-mesh
    volumes:
      # 1. 掛載資料庫連線設定
      - ./grafana-config/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      # 2. 掛載儀表板讀取路徑設定
      - ./grafana-config/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      # 3. 實際存放 JSON 檔案的地方
      - ./grafana-config/dashboards/dashboard1.json:/var/lib/grafana/dashboards/my_waf_dashboard.json
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true  # 免登入直接看，交作業好用
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  
  llm-analyzer:
    build: ./llm_analyzer  # 建立一個新的資料夾放這支程式
    env_file:
      - .env
    container_name: llm-analyzer
    ports:
      - "5001:5001" # 獨立一個 port 給它
    networks:
      - envoy-mesh
    restart: unless-stopped

networks:
  envoy-mesh:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

